Bookkeeping Integration
AliceO2Group/Control pull request #207
Opened 2021-02-05 15:21 UTC by miltalex

2021-02-05 15:23 UTC, miltalex commented on core/bookkeeping/api.go
> +// This package instantiates the bookkeeping API client. There is one
@teo make build should fail with error
```
vendor/github.com/AliceO2Group/Bookkeeping/go-api-client/src/BookkeepingApi.go:5:8: local import "./go-client-generated" in non-local package
```

2021-02-15 19:48 UTC, miltalex commented on core/bookkeeping/api.go
> +	bookkeepingBaseUrl       = "http://vm4.jiskefet.io/api"
Notice: Should point to the endpoint hosted in the head node.

2021-05-05 08:02 UTC, teo requested changes

2021-05-05 08:02 UTC, teo commented on core/environment/environment.go
> +	if runtype, ok := varStack["runtype"]; ok {
It's `run_type` in the `varStack`

2021-05-05 08:02 UTC, teo commented on core/environment/transition_startactivity.go
> +	// the.BookkeepingAPI().CreateLog(env.Id().String(), fmt.Sprintf("Log for run %s and environment %s",runNumberStr,env.Id().String()), runNumberStr, -1)
Ok, could you please create a short JIRA ticket on this?

2021-05-05 08:14 UTC, miltalex commented on core/bookkeeping/api.go
> +	clientAPI.CreateLog(text, title, runNumbers, parentLogId)
The Bookkeeping API is expecting a `runNumbers` string entity `func CreateLog(text string, title string, runNumbers string, parentLogId int32)`

2021-05-05 10:56 UTC, merged